// <auto-generated />
using System;
using BitcoinPriceTracking.BE.DB.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitcoinPriceTracking.BE.DB.Migrations.MSSQL
{
    [DbContext(typeof(MsSqlDbContext))]
    [Migration("20251018211608_inicialization")]
    partial class inicialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitcoinPriceTracking.BE.DB.Models.Entities.CryptoData", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<string>("BASE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BASE_ID")
                        .HasColumnType("float")
                        .HasColumnName("BASE_ID")
                        .HasComment("test");

                    b.Property<double>("BEST_ASK")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_LAST_UPDATE_TS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_LAST_UPDATE_TS_NS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_POSITION_IN_BOOK_UPDATE_TS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_POSITION_IN_BOOK_UPDATE_TS_NS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("BEST_ASK_QUOTE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_LAST_UPDATE_TS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_LAST_UPDATE_TS_NS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_POSITION_IN_BOOK_UPDATE_TS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_POSITION_IN_BOOK_UPDATE_TS_NS")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("BEST_BID_QUOTE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("CCSEQ")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_LOW")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_HOUR_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_LOW")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_MONTH_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_LOW")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_WEEK_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_LOW")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("CURRENT_YEAR_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<string>("INSTRUMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LAST_PROCESSED_TRADE_CCSEQ")
                        .HasColumnType("float");

                    b.Property<double>("LAST_PROCESSED_TRADE_PRICE")
                        .HasColumnType("float");

                    b.Property<double>("LAST_PROCESSED_TRADE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("LAST_PROCESSED_TRADE_QUOTE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<string>("LAST_PROCESSED_TRADE_SIDE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LAST_PROCESSED_TRADE_TS")
                        .HasColumnType("float");

                    b.Property<double>("LAST_PROCESSED_TRADE_TS_NS")
                        .HasColumnType("float");

                    b.Property<double>("LAST_TRADE_CCSEQ")
                        .HasColumnType("float");

                    b.Property<string>("LAST_TRADE_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LAST_TRADE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<double>("LAST_TRADE_QUOTE_QUANTITY")
                        .HasColumnType("float");

                    b.Property<string>("LAST_TRADE_SIDE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LIFETIME_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_FIRST_TRADE_TS")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_HIGH_TS")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_LOW")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_LOW_TS")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("LIFETIME_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<string>("MAPPED_INSTRUMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MARKET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MOVING_180_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_180_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_24_HOUR_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_30_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_365_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_7_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_CHANGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_CHANGE_PERCENTAGE")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_HIGH")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_LOW")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_OPEN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_QUOTE_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_QUOTE_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_QUOTE_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_QUOTE_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_TOTAL_TRADES")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_TOTAL_TRADES_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_TOTAL_TRADES_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_TOTAL_TRADES_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_VOLUME")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_VOLUME_BUY")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_VOLUME_SELL")
                        .HasColumnType("float");

                    b.Property<double>("MOVING_90_DAY_VOLUME_UNKNOWN")
                        .HasColumnType("float");

                    b.Property<double>("PRICE")
                        .HasColumnType("float");

                    b.Property<string>("PRICE_FLAG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PRICE_LAST_UPDATE_TS")
                        .HasColumnType("float");

                    b.Property<double>("PRICE_LAST_UPDATE_TS_NS")
                        .HasColumnType("float");

                    b.Property<string>("QUOTE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QUOTE_ID")
                        .HasColumnType("float");

                    b.Property<string>("TRANSFORM_FUNCTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Crypto_datas", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
