using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BitcoinPriceTracking.BE.DB.Migrations.MSSQL
{
    /// <inheritdoc />
    public partial class inicialization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "dbo");

            migrationBuilder.CreateTable(
                name: "Crypto_datas",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<double>(type: "float", nullable: false),
                    BASE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BASE_ID = table.Column<double>(type: "float", nullable: false, comment: "test"),
                    BEST_ASK = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_LAST_UPDATE_TS = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_LAST_UPDATE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_POSITION_IN_BOOK_UPDATE_TS = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_POSITION_IN_BOOK_UPDATE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    BEST_ASK_QUOTE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    BEST_BID = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_LAST_UPDATE_TS = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_LAST_UPDATE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_POSITION_IN_BOOK_UPDATE_TS = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_POSITION_IN_BOOK_UPDATE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    BEST_BID_QUOTE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    CCSEQ = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_HIGH = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_CHANGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_LOW = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_OPEN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_HOUR_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_HIGH = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_CHANGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_LOW = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_OPEN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_MONTH_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_HIGH = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_CHANGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_LOW = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_OPEN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_WEEK_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_HIGH = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_CHANGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_LOW = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_OPEN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_VOLUME = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    CURRENT_YEAR_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    INSTRUMENT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LAST_PROCESSED_TRADE_CCSEQ = table.Column<double>(type: "float", nullable: false),
                    LAST_PROCESSED_TRADE_PRICE = table.Column<double>(type: "float", nullable: false),
                    LAST_PROCESSED_TRADE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    LAST_PROCESSED_TRADE_QUOTE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    LAST_PROCESSED_TRADE_SIDE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LAST_PROCESSED_TRADE_TS = table.Column<double>(type: "float", nullable: false),
                    LAST_PROCESSED_TRADE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    LAST_TRADE_CCSEQ = table.Column<double>(type: "float", nullable: false),
                    LAST_TRADE_ID = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LAST_TRADE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    LAST_TRADE_QUOTE_QUANTITY = table.Column<double>(type: "float", nullable: false),
                    LAST_TRADE_SIDE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LIFETIME_FIRST_TRADE_TS = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_HIGH = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_HIGH_TS = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_CHANGE = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_LOW = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_LOW_TS = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_OPEN = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_VOLUME = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    LIFETIME_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MAPPED_INSTRUMENT = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MARKET = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MOVING_180_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_180_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_24_HOUR_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_30_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_365_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_7_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_HIGH = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_CHANGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_CHANGE_PERCENTAGE = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_LOW = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_OPEN = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_QUOTE_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_QUOTE_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_QUOTE_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_QUOTE_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_TOTAL_TRADES = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_TOTAL_TRADES_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_TOTAL_TRADES_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_TOTAL_TRADES_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_VOLUME = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_VOLUME_BUY = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_VOLUME_SELL = table.Column<double>(type: "float", nullable: false),
                    MOVING_90_DAY_VOLUME_UNKNOWN = table.Column<double>(type: "float", nullable: false),
                    PRICE = table.Column<double>(type: "float", nullable: false),
                    PRICE_FLAG = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PRICE_LAST_UPDATE_TS = table.Column<double>(type: "float", nullable: false),
                    PRICE_LAST_UPDATE_TS_NS = table.Column<double>(type: "float", nullable: false),
                    QUOTE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    QUOTE_ID = table.Column<double>(type: "float", nullable: false),
                    TRANSFORM_FUNCTION = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TYPE = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TimeStamp = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Crypto_datas", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Crypto_datas",
                schema: "dbo");
        }
    }
}
