namespace BitcoinPriceTracking.BE.BusinessLogic.Models.DTOs
{
	public class CryptoDataDto : ICryptoData
	{
		public string BASE { get; set; }
		public int BASE_ID { get; set; }
		public float BEST_ASK { get; set; }
		public int BEST_ASK_LAST_UPDATE_TS { get; set; }
		public int BEST_ASK_LAST_UPDATE_TS_NS { get; set; }
		public int BEST_ASK_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		public int BEST_ASK_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		public float BEST_ASK_QUANTITY { get; set; }
		public float BEST_ASK_QUOTE_QUANTITY { get; set; }
		public float BEST_BID { get; set; }
		public int BEST_BID_LAST_UPDATE_TS { get; set; }
		public int BEST_BID_LAST_UPDATE_TS_NS { get; set; }
		public int BEST_BID_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		public int BEST_BID_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		public float BEST_BID_QUANTITY { get; set; }
		public float BEST_BID_QUOTE_QUANTITY { get; set; }
		public int CCSEQ { get; set; }
		public float CURRENT_DAY_HIGH { get; set; }
		public float CURRENT_DAY_CHANGE { get; set; }
		public float CURRENT_DAY_CHANGE_PERCENTAGE { get; set; }
		public float CURRENT_DAY_LOW { get; set; }
		public float CURRENT_DAY_OPEN { get; set; }
		public float CURRENT_DAY_QUOTE_VOLUME { get; set; }
		public float CURRENT_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float CURRENT_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int CURRENT_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int CURRENT_DAY_TOTAL_TRADES { get; set; }
		public int CURRENT_DAY_TOTAL_TRADES_BUY { get; set; }
		public int CURRENT_DAY_TOTAL_TRADES_SELL { get; set; }
		public int CURRENT_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float CURRENT_DAY_VOLUME { get; set; }
		public float CURRENT_DAY_VOLUME_BUY { get; set; }
		public float CURRENT_DAY_VOLUME_SELL { get; set; }
		public int CURRENT_DAY_VOLUME_UNKNOWN { get; set; }
		public float CURRENT_HOUR_HIGH { get; set; }
		public float CURRENT_HOUR_CHANGE { get; set; }
		public float CURRENT_HOUR_CHANGE_PERCENTAGE { get; set; }
		public float CURRENT_HOUR_LOW { get; set; }
		public float CURRENT_HOUR_OPEN { get; set; }
		public float CURRENT_HOUR_QUOTE_VOLUME { get; set; }
		public float CURRENT_HOUR_QUOTE_VOLUME_BUY { get; set; }
		public float CURRENT_HOUR_QUOTE_VOLUME_SELL { get; set; }
		public int CURRENT_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int CURRENT_HOUR_TOTAL_TRADES { get; set; }
		public int CURRENT_HOUR_TOTAL_TRADES_BUY { get; set; }
		public int CURRENT_HOUR_TOTAL_TRADES_SELL { get; set; }
		public int CURRENT_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		public float CURRENT_HOUR_VOLUME { get; set; }
		public float CURRENT_HOUR_VOLUME_BUY { get; set; }
		public float CURRENT_HOUR_VOLUME_SELL { get; set; }
		public int CURRENT_HOUR_VOLUME_UNKNOWN { get; set; }
		public float CURRENT_MONTH_HIGH { get; set; }
		public float CURRENT_MONTH_CHANGE { get; set; }
		public float CURRENT_MONTH_CHANGE_PERCENTAGE { get; set; }
		public int CURRENT_MONTH_LOW { get; set; }
		public float CURRENT_MONTH_OPEN { get; set; }
		public float CURRENT_MONTH_QUOTE_VOLUME { get; set; }
		public float CURRENT_MONTH_QUOTE_VOLUME_BUY { get; set; }
		public float CURRENT_MONTH_QUOTE_VOLUME_SELL { get; set; }
		public int CURRENT_MONTH_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int CURRENT_MONTH_TOTAL_TRADES { get; set; }
		public int CURRENT_MONTH_TOTAL_TRADES_BUY { get; set; }
		public int CURRENT_MONTH_TOTAL_TRADES_SELL { get; set; }
		public int CURRENT_MONTH_TOTAL_TRADES_UNKNOWN { get; set; }
		public float CURRENT_MONTH_VOLUME { get; set; }
		public float CURRENT_MONTH_VOLUME_BUY { get; set; }
		public float CURRENT_MONTH_VOLUME_SELL { get; set; }
		public int CURRENT_MONTH_VOLUME_UNKNOWN { get; set; }
		public float CURRENT_WEEK_HIGH { get; set; }
		public float CURRENT_WEEK_CHANGE { get; set; }
		public float CURRENT_WEEK_CHANGE_PERCENTAGE { get; set; }
		public float CURRENT_WEEK_LOW { get; set; }
		public float CURRENT_WEEK_OPEN { get; set; }
		public float CURRENT_WEEK_QUOTE_VOLUME { get; set; }
		public float CURRENT_WEEK_QUOTE_VOLUME_BUY { get; set; }
		public float CURRENT_WEEK_QUOTE_VOLUME_SELL { get; set; }
		public int CURRENT_WEEK_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int CURRENT_WEEK_TOTAL_TRADES { get; set; }
		public int CURRENT_WEEK_TOTAL_TRADES_BUY { get; set; }
		public int CURRENT_WEEK_TOTAL_TRADES_SELL { get; set; }
		public int CURRENT_WEEK_TOTAL_TRADES_UNKNOWN { get; set; }
		public float CURRENT_WEEK_VOLUME { get; set; }
		public float CURRENT_WEEK_VOLUME_BUY { get; set; }
		public float CURRENT_WEEK_VOLUME_SELL { get; set; }
		public int CURRENT_WEEK_VOLUME_UNKNOWN { get; set; }
		public float CURRENT_YEAR_HIGH { get; set; }
		public float CURRENT_YEAR_CHANGE { get; set; }
		public float CURRENT_YEAR_CHANGE_PERCENTAGE { get; set; }
		public int CURRENT_YEAR_LOW { get; set; }
		public float CURRENT_YEAR_OPEN { get; set; }
		public float CURRENT_YEAR_QUOTE_VOLUME { get; set; }
		public float CURRENT_YEAR_QUOTE_VOLUME_BUY { get; set; }
		public float CURRENT_YEAR_QUOTE_VOLUME_SELL { get; set; }
		public int CURRENT_YEAR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int CURRENT_YEAR_TOTAL_TRADES { get; set; }
		public int CURRENT_YEAR_TOTAL_TRADES_BUY { get; set; }
		public int CURRENT_YEAR_TOTAL_TRADES_SELL { get; set; }
		public int CURRENT_YEAR_TOTAL_TRADES_UNKNOWN { get; set; }
		public float CURRENT_YEAR_VOLUME { get; set; }
		public float CURRENT_YEAR_VOLUME_BUY { get; set; }
		public float CURRENT_YEAR_VOLUME_SELL { get; set; }
		public int CURRENT_YEAR_VOLUME_UNKNOWN { get; set; }
		public string INSTRUMENT { get; set; }
		public int LAST_PROCESSED_TRADE_CCSEQ { get; set; }
		public float LAST_PROCESSED_TRADE_PRICE { get; set; }
		public float LAST_PROCESSED_TRADE_QUANTITY { get; set; }
		public float LAST_PROCESSED_TRADE_QUOTE_QUANTITY { get; set; }
		public string LAST_PROCESSED_TRADE_SIDE { get; set; }
		public int LAST_PROCESSED_TRADE_TS { get; set; }
		public int LAST_PROCESSED_TRADE_TS_NS { get; set; }
		public int LAST_TRADE_CCSEQ { get; set; }
		public string LAST_TRADE_ID { get; set; }
		public float LAST_TRADE_QUANTITY { get; set; }
		public float LAST_TRADE_QUOTE_QUANTITY { get; set; }
		public string LAST_TRADE_SIDE { get; set; }
		public int LIFETIME_FIRST_TRADE_TS { get; set; }
		public float LIFETIME_HIGH { get; set; }
		public int LIFETIME_HIGH_TS { get; set; }
		public float LIFETIME_CHANGE { get; set; }
		public float LIFETIME_CHANGE_PERCENTAGE { get; set; }
		public float LIFETIME_LOW { get; set; }
		public int LIFETIME_LOW_TS { get; set; }
		public int LIFETIME_OPEN { get; set; }
		public float LIFETIME_QUOTE_VOLUME { get; set; }
		public float LIFETIME_QUOTE_VOLUME_BUY { get; set; }
		public float LIFETIME_QUOTE_VOLUME_SELL { get; set; }
		public int LIFETIME_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int LIFETIME_TOTAL_TRADES { get; set; }
		public int LIFETIME_TOTAL_TRADES_BUY { get; set; }
		public int LIFETIME_TOTAL_TRADES_SELL { get; set; }
		public int LIFETIME_TOTAL_TRADES_UNKNOWN { get; set; }
		public float LIFETIME_VOLUME { get; set; }
		public float LIFETIME_VOLUME_BUY { get; set; }
		public float LIFETIME_VOLUME_SELL { get; set; }
		public int LIFETIME_VOLUME_UNKNOWN { get; set; }
		public string MAPPED_INSTRUMENT { get; set; }
		public string MARKET { get; set; }
		public float MOVING_180_DAY_HIGH { get; set; }
		public float MOVING_180_DAY_CHANGE { get; set; }
		public float MOVING_180_DAY_CHANGE_PERCENTAGE { get; set; }
		public float MOVING_180_DAY_LOW { get; set; }
		public float MOVING_180_DAY_OPEN { get; set; }
		public float MOVING_180_DAY_QUOTE_VOLUME { get; set; }
		public float MOVING_180_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_180_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_180_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_180_DAY_TOTAL_TRADES { get; set; }
		public int MOVING_180_DAY_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_180_DAY_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_180_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_180_DAY_VOLUME { get; set; }
		public float MOVING_180_DAY_VOLUME_BUY { get; set; }
		public float MOVING_180_DAY_VOLUME_SELL { get; set; }
		public int MOVING_180_DAY_VOLUME_UNKNOWN { get; set; }
		public float MOVING_24_HOUR_HIGH { get; set; }
		public float MOVING_24_HOUR_CHANGE { get; set; }
		public float MOVING_24_HOUR_CHANGE_PERCENTAGE { get; set; }
		public float MOVING_24_HOUR_LOW { get; set; }
		public float MOVING_24_HOUR_OPEN { get; set; }
		public float MOVING_24_HOUR_QUOTE_VOLUME { get; set; }
		public float MOVING_24_HOUR_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_24_HOUR_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_24_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_24_HOUR_TOTAL_TRADES { get; set; }
		public int MOVING_24_HOUR_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_24_HOUR_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_24_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_24_HOUR_VOLUME { get; set; }
		public float MOVING_24_HOUR_VOLUME_BUY { get; set; }
		public float MOVING_24_HOUR_VOLUME_SELL { get; set; }
		public int MOVING_24_HOUR_VOLUME_UNKNOWN { get; set; }
		public float MOVING_30_DAY_HIGH { get; set; }
		public float MOVING_30_DAY_CHANGE { get; set; }
		public float MOVING_30_DAY_CHANGE_PERCENTAGE { get; set; }
		public int MOVING_30_DAY_LOW { get; set; }
		public float MOVING_30_DAY_OPEN { get; set; }
		public float MOVING_30_DAY_QUOTE_VOLUME { get; set; }
		public float MOVING_30_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_30_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_30_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_30_DAY_TOTAL_TRADES { get; set; }
		public int MOVING_30_DAY_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_30_DAY_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_30_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_30_DAY_VOLUME { get; set; }
		public float MOVING_30_DAY_VOLUME_BUY { get; set; }
		public float MOVING_30_DAY_VOLUME_SELL { get; set; }
		public int MOVING_30_DAY_VOLUME_UNKNOWN { get; set; }
		public float MOVING_365_DAY_HIGH { get; set; }
		public float MOVING_365_DAY_CHANGE { get; set; }
		public float MOVING_365_DAY_CHANGE_PERCENTAGE { get; set; }
		public int MOVING_365_DAY_LOW { get; set; }
		public float MOVING_365_DAY_OPEN { get; set; }
		public float MOVING_365_DAY_QUOTE_VOLUME { get; set; }
		public float MOVING_365_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_365_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_365_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_365_DAY_TOTAL_TRADES { get; set; }
		public int MOVING_365_DAY_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_365_DAY_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_365_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_365_DAY_VOLUME { get; set; }
		public float MOVING_365_DAY_VOLUME_BUY { get; set; }
		public float MOVING_365_DAY_VOLUME_SELL { get; set; }
		public int MOVING_365_DAY_VOLUME_UNKNOWN { get; set; }
		public float MOVING_7_DAY_HIGH { get; set; }
		public float MOVING_7_DAY_CHANGE { get; set; }
		public float MOVING_7_DAY_CHANGE_PERCENTAGE { get; set; }
		public int MOVING_7_DAY_LOW { get; set; }
		public float MOVING_7_DAY_OPEN { get; set; }
		public float MOVING_7_DAY_QUOTE_VOLUME { get; set; }
		public float MOVING_7_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_7_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_7_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_7_DAY_TOTAL_TRADES { get; set; }
		public int MOVING_7_DAY_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_7_DAY_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_7_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_7_DAY_VOLUME { get; set; }
		public float MOVING_7_DAY_VOLUME_BUY { get; set; }
		public float MOVING_7_DAY_VOLUME_SELL { get; set; }
		public int MOVING_7_DAY_VOLUME_UNKNOWN { get; set; }
		public float MOVING_90_DAY_HIGH { get; set; }
		public float MOVING_90_DAY_CHANGE { get; set; }
		public float MOVING_90_DAY_CHANGE_PERCENTAGE { get; set; }
		public int MOVING_90_DAY_LOW { get; set; }
		public float MOVING_90_DAY_OPEN { get; set; }
		public float MOVING_90_DAY_QUOTE_VOLUME { get; set; }
		public float MOVING_90_DAY_QUOTE_VOLUME_BUY { get; set; }
		public float MOVING_90_DAY_QUOTE_VOLUME_SELL { get; set; }
		public int MOVING_90_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public int MOVING_90_DAY_TOTAL_TRADES { get; set; }
		public int MOVING_90_DAY_TOTAL_TRADES_BUY { get; set; }
		public int MOVING_90_DAY_TOTAL_TRADES_SELL { get; set; }
		public int MOVING_90_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public float MOVING_90_DAY_VOLUME { get; set; }
		public float MOVING_90_DAY_VOLUME_BUY { get; set; }
		public float MOVING_90_DAY_VOLUME_SELL { get; set; }
		public int MOVING_90_DAY_VOLUME_UNKNOWN { get; set; }
		public float PRICE { get; set; }
		public string PRICE_FLAG { get; set; }
		public int PRICE_LAST_UPDATE_TS { get; set; }
		public int PRICE_LAST_UPDATE_TS_NS { get; set; }
		public string QUOTE { get; set; }
		public int QUOTE_ID { get; set; }
		public string TRANSFORM_FUNCTION { get; set; }
		public string TYPE { get; set; }
	}
}
