using BitcoinPriceTracking.BE.Shared.Interfaces.Models;

namespace BitcoinPriceTracking.BE.Shared.Models.DTOs
{
	public class CryptoDataBaseDTO : ICryptoData
	{
		public int Id { get; set; }
		public string TYPE { get; set; } = string.Empty;
		public string MARKET { get; set; } = string.Empty;
		public string INSTRUMENT { get; set; } = string.Empty;
		public string MAPPED_INSTRUMENT { get; set; } = string.Empty;
		public string BASE { get; set; } = string.Empty;
		public string QUOTE { get; set; } = string.Empty;
		public double BASE_ID { get; set; }
		public double QUOTE_ID { get; set; }
		public string TRANSFORM_FUNCTION { get; set; } = string.Empty;
		public double CCSEQ { get; set; }
		public double PRICE { get; set; }
		public string PRICE_FLAG { get; set; } = string.Empty;
		public double PRICE_LAST_UPDATE_TS { get; set; }
		public double PRICE_LAST_UPDATE_TS_NS { get; set; }
		public double LAST_TRADE_QUANTITY { get; set; }
		public double LAST_TRADE_QUOTE_QUANTITY { get; set; }
		public string LAST_TRADE_ID { get; set; } = string.Empty;
		public double LAST_TRADE_CCSEQ { get; set; }
		public string LAST_TRADE_SIDE { get; set; } = string.Empty;
		public double LAST_PROCESSED_TRADE_TS { get; set; }
		public double LAST_PROCESSED_TRADE_TS_NS { get; set; }
		public double LAST_PROCESSED_TRADE_PRICE { get; set; }
		public double LAST_PROCESSED_TRADE_QUANTITY { get; set; }
		public double LAST_PROCESSED_TRADE_QUOTE_QUANTITY { get; set; }
		public string LAST_PROCESSED_TRADE_SIDE { get; set; } = string.Empty;
		public double LAST_PROCESSED_TRADE_CCSEQ { get; set; }
		public double BEST_BID { get; set; }
		public double BEST_BID_QUANTITY { get; set; }
		public double BEST_BID_QUOTE_QUANTITY { get; set; }
		public double BEST_BID_LAST_UPDATE_TS { get; set; }
		public double BEST_BID_LAST_UPDATE_TS_NS { get; set; }
		public double BEST_BID_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		public double BEST_BID_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		public double BEST_ASK { get; set; }
		public double BEST_ASK_QUANTITY { get; set; }
		public double BEST_ASK_QUOTE_QUANTITY { get; set; }
		public double BEST_ASK_LAST_UPDATE_TS { get; set; }
		public double BEST_ASK_LAST_UPDATE_TS_NS { get; set; }
		public double BEST_ASK_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		public double BEST_ASK_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		public double CURRENT_HOUR_VOLUME { get; set; }
		public double CURRENT_HOUR_VOLUME_BUY { get; set; }
		public double CURRENT_HOUR_VOLUME_SELL { get; set; }
		public double CURRENT_HOUR_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_HOUR_QUOTE_VOLUME { get; set; }
		public double CURRENT_HOUR_QUOTE_VOLUME_BUY { get; set; }
		public double CURRENT_HOUR_QUOTE_VOLUME_SELL { get; set; }
		public double CURRENT_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_HOUR_OPEN { get; set; }
		public double CURRENT_HOUR_HIGH { get; set; }
		public double CURRENT_HOUR_LOW { get; set; }
		public double CURRENT_HOUR_TOTAL_TRADES { get; set; }
		public double CURRENT_HOUR_TOTAL_TRADES_BUY { get; set; }
		public double CURRENT_HOUR_TOTAL_TRADES_SELL { get; set; }
		public double CURRENT_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		public double CURRENT_HOUR_CHANGE { get; set; }
		public double CURRENT_HOUR_CHANGE_PERCENTAGE { get; set; }
		public double CURRENT_DAY_VOLUME { get; set; }
		public double CURRENT_DAY_VOLUME_BUY { get; set; }
		public double CURRENT_DAY_VOLUME_SELL { get; set; }
		public double CURRENT_DAY_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_DAY_QUOTE_VOLUME { get; set; }
		public double CURRENT_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double CURRENT_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double CURRENT_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_DAY_OPEN { get; set; }
		public double CURRENT_DAY_HIGH { get; set; }
		public double CURRENT_DAY_LOW { get; set; }
		public double CURRENT_DAY_TOTAL_TRADES { get; set; }
		public double CURRENT_DAY_TOTAL_TRADES_BUY { get; set; }
		public double CURRENT_DAY_TOTAL_TRADES_SELL { get; set; }
		public double CURRENT_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double CURRENT_DAY_CHANGE { get; set; }
		public double CURRENT_DAY_CHANGE_PERCENTAGE { get; set; }
		public double CURRENT_WEEK_VOLUME { get; set; }
		public double CURRENT_WEEK_VOLUME_BUY { get; set; }
		public double CURRENT_WEEK_VOLUME_SELL { get; set; }
		public double CURRENT_WEEK_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_WEEK_QUOTE_VOLUME { get; set; }
		public double CURRENT_WEEK_QUOTE_VOLUME_BUY { get; set; }
		public double CURRENT_WEEK_QUOTE_VOLUME_SELL { get; set; }
		public double CURRENT_WEEK_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_WEEK_OPEN { get; set; }
		public double CURRENT_WEEK_HIGH { get; set; }
		public double CURRENT_WEEK_LOW { get; set; }
		public double CURRENT_WEEK_TOTAL_TRADES { get; set; }
		public double CURRENT_WEEK_TOTAL_TRADES_BUY { get; set; }
		public double CURRENT_WEEK_TOTAL_TRADES_SELL { get; set; }
		public double CURRENT_WEEK_TOTAL_TRADES_UNKNOWN { get; set; }
		public double CURRENT_WEEK_CHANGE { get; set; }
		public double CURRENT_WEEK_CHANGE_PERCENTAGE { get; set; }
		public double CURRENT_MONTH_VOLUME { get; set; }
		public double CURRENT_MONTH_VOLUME_BUY { get; set; }
		public double CURRENT_MONTH_VOLUME_SELL { get; set; }
		public double CURRENT_MONTH_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_MONTH_QUOTE_VOLUME { get; set; }
		public double CURRENT_MONTH_QUOTE_VOLUME_BUY { get; set; }
		public double CURRENT_MONTH_QUOTE_VOLUME_SELL { get; set; }
		public double CURRENT_MONTH_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_MONTH_OPEN { get; set; }
		public double CURRENT_MONTH_HIGH { get; set; }
		public double CURRENT_MONTH_LOW { get; set; }
		public double CURRENT_MONTH_TOTAL_TRADES { get; set; }
		public double CURRENT_MONTH_TOTAL_TRADES_BUY { get; set; }
		public double CURRENT_MONTH_TOTAL_TRADES_SELL { get; set; }
		public double CURRENT_MONTH_TOTAL_TRADES_UNKNOWN { get; set; }
		public double CURRENT_MONTH_CHANGE { get; set; }
		public double CURRENT_MONTH_CHANGE_PERCENTAGE { get; set; }
		public double CURRENT_YEAR_VOLUME { get; set; }
		public double CURRENT_YEAR_VOLUME_BUY { get; set; }
		public double CURRENT_YEAR_VOLUME_SELL { get; set; }
		public double CURRENT_YEAR_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_YEAR_QUOTE_VOLUME { get; set; }
		public double CURRENT_YEAR_QUOTE_VOLUME_BUY { get; set; }
		public double CURRENT_YEAR_QUOTE_VOLUME_SELL { get; set; }
		public double CURRENT_YEAR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double CURRENT_YEAR_OPEN { get; set; }
		public double CURRENT_YEAR_HIGH { get; set; }
		public double CURRENT_YEAR_LOW { get; set; }
		public double CURRENT_YEAR_TOTAL_TRADES { get; set; }
		public double CURRENT_YEAR_TOTAL_TRADES_BUY { get; set; }
		public double CURRENT_YEAR_TOTAL_TRADES_SELL { get; set; }
		public double CURRENT_YEAR_TOTAL_TRADES_UNKNOWN { get; set; }
		public double CURRENT_YEAR_CHANGE { get; set; }
		public double CURRENT_YEAR_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_24_HOUR_VOLUME { get; set; }
		public double MOVING_24_HOUR_VOLUME_BUY { get; set; }
		public double MOVING_24_HOUR_VOLUME_SELL { get; set; }
		public double MOVING_24_HOUR_VOLUME_UNKNOWN { get; set; }
		public double MOVING_24_HOUR_QUOTE_VOLUME { get; set; }
		public double MOVING_24_HOUR_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_24_HOUR_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_24_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_24_HOUR_OPEN { get; set; }
		public double MOVING_24_HOUR_HIGH { get; set; }
		public double MOVING_24_HOUR_LOW { get; set; }
		public double MOVING_24_HOUR_TOTAL_TRADES { get; set; }
		public double MOVING_24_HOUR_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_24_HOUR_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_24_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_24_HOUR_CHANGE { get; set; }
		public double MOVING_24_HOUR_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_7_DAY_VOLUME { get; set; }
		public double MOVING_7_DAY_VOLUME_BUY { get; set; }
		public double MOVING_7_DAY_VOLUME_SELL { get; set; }
		public double MOVING_7_DAY_VOLUME_UNKNOWN { get; set; }
		public double MOVING_7_DAY_QUOTE_VOLUME { get; set; }
		public double MOVING_7_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_7_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_7_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_7_DAY_OPEN { get; set; }
		public double MOVING_7_DAY_HIGH { get; set; }
		public double MOVING_7_DAY_LOW { get; set; }
		public double MOVING_7_DAY_TOTAL_TRADES { get; set; }
		public double MOVING_7_DAY_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_7_DAY_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_7_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_7_DAY_CHANGE { get; set; }
		public double MOVING_7_DAY_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_30_DAY_VOLUME { get; set; }
		public double MOVING_30_DAY_VOLUME_BUY { get; set; }
		public double MOVING_30_DAY_VOLUME_SELL { get; set; }
		public double MOVING_30_DAY_VOLUME_UNKNOWN { get; set; }
		public double MOVING_30_DAY_QUOTE_VOLUME { get; set; }
		public double MOVING_30_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_30_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_30_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_30_DAY_OPEN { get; set; }
		public double MOVING_30_DAY_HIGH { get; set; }
		public double MOVING_30_DAY_LOW { get; set; }
		public double MOVING_30_DAY_TOTAL_TRADES { get; set; }
		public double MOVING_30_DAY_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_30_DAY_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_30_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_30_DAY_CHANGE { get; set; }
		public double MOVING_30_DAY_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_90_DAY_VOLUME { get; set; }
		public double MOVING_90_DAY_VOLUME_BUY { get; set; }
		public double MOVING_90_DAY_VOLUME_SELL { get; set; }
		public double MOVING_90_DAY_VOLUME_UNKNOWN { get; set; }
		public double MOVING_90_DAY_QUOTE_VOLUME { get; set; }
		public double MOVING_90_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_90_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_90_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_90_DAY_OPEN { get; set; }
		public double MOVING_90_DAY_HIGH { get; set; }
		public double MOVING_90_DAY_LOW { get; set; }
		public double MOVING_90_DAY_TOTAL_TRADES { get; set; }
		public double MOVING_90_DAY_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_90_DAY_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_90_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_90_DAY_CHANGE { get; set; }
		public double MOVING_90_DAY_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_180_DAY_VOLUME { get; set; }
		public double MOVING_180_DAY_VOLUME_BUY { get; set; }
		public double MOVING_180_DAY_VOLUME_SELL { get; set; }
		public double MOVING_180_DAY_VOLUME_UNKNOWN { get; set; }
		public double MOVING_180_DAY_QUOTE_VOLUME { get; set; }
		public double MOVING_180_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_180_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_180_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_180_DAY_OPEN { get; set; }
		public double MOVING_180_DAY_HIGH { get; set; }
		public double MOVING_180_DAY_LOW { get; set; }
		public double MOVING_180_DAY_TOTAL_TRADES { get; set; }
		public double MOVING_180_DAY_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_180_DAY_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_180_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_180_DAY_CHANGE { get; set; }
		public double MOVING_180_DAY_CHANGE_PERCENTAGE { get; set; }
		public double MOVING_365_DAY_VOLUME { get; set; }
		public double MOVING_365_DAY_VOLUME_BUY { get; set; }
		public double MOVING_365_DAY_VOLUME_SELL { get; set; }
		public double MOVING_365_DAY_VOLUME_UNKNOWN { get; set; }
		public double MOVING_365_DAY_QUOTE_VOLUME { get; set; }
		public double MOVING_365_DAY_QUOTE_VOLUME_BUY { get; set; }
		public double MOVING_365_DAY_QUOTE_VOLUME_SELL { get; set; }
		public double MOVING_365_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double MOVING_365_DAY_OPEN { get; set; }
		public double MOVING_365_DAY_HIGH { get; set; }
		public double MOVING_365_DAY_LOW { get; set; }
		public double MOVING_365_DAY_TOTAL_TRADES { get; set; }
		public double MOVING_365_DAY_TOTAL_TRADES_BUY { get; set; }
		public double MOVING_365_DAY_TOTAL_TRADES_SELL { get; set; }
		public double MOVING_365_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		public double MOVING_365_DAY_CHANGE { get; set; }
		public double MOVING_365_DAY_CHANGE_PERCENTAGE { get; set; }
		public double LIFETIME_FIRST_TRADE_TS { get; set; }
		public double LIFETIME_VOLUME { get; set; }
		public double LIFETIME_VOLUME_BUY { get; set; }
		public double LIFETIME_VOLUME_SELL { get; set; }
		public double LIFETIME_VOLUME_UNKNOWN { get; set; }
		public double LIFETIME_QUOTE_VOLUME { get; set; }
		public double LIFETIME_QUOTE_VOLUME_BUY { get; set; }
		public double LIFETIME_QUOTE_VOLUME_SELL { get; set; }
		public double LIFETIME_QUOTE_VOLUME_UNKNOWN { get; set; }
		public double LIFETIME_OPEN { get; set; }
		public double LIFETIME_HIGH { get; set; }
		public double LIFETIME_HIGH_TS { get; set; }
		public double LIFETIME_LOW { get; set; }
		public double LIFETIME_LOW_TS { get; set; }
		public double LIFETIME_TOTAL_TRADES { get; set; }
		public double LIFETIME_TOTAL_TRADES_BUY { get; set; }
		public double LIFETIME_TOTAL_TRADES_SELL { get; set; }
		public double LIFETIME_TOTAL_TRADES_UNKNOWN { get; set; }
		public double LIFETIME_CHANGE { get; set; }
		public double LIFETIME_CHANGE_PERCENTAGE { get; set; }
	}
}