namespace BitcoinPriceTracking.BE.BusinessLogic.Models
{
	public interface ICryptoData
	{
		string BASE { get; set; }
		int BASE_ID { get; set; }
		float BEST_ASK { get; set; }
		int BEST_ASK_LAST_UPDATE_TS { get; set; }
		int BEST_ASK_LAST_UPDATE_TS_NS { get; set; }
		int BEST_ASK_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		int BEST_ASK_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		float BEST_ASK_QUANTITY { get; set; }
		float BEST_ASK_QUOTE_QUANTITY { get; set; }
		float BEST_BID { get; set; }
		int BEST_BID_LAST_UPDATE_TS { get; set; }
		int BEST_BID_LAST_UPDATE_TS_NS { get; set; }
		int BEST_BID_POSITION_IN_BOOK_UPDATE_TS { get; set; }
		int BEST_BID_POSITION_IN_BOOK_UPDATE_TS_NS { get; set; }
		float BEST_BID_QUANTITY { get; set; }
		float BEST_BID_QUOTE_QUANTITY { get; set; }
		int CCSEQ { get; set; }
		float CURRENT_DAY_HIGH { get; set; }
		float CURRENT_DAY_CHANGE { get; set; }
		float CURRENT_DAY_CHANGE_PERCENTAGE { get; set; }
		float CURRENT_DAY_LOW { get; set; }
		float CURRENT_DAY_OPEN { get; set; }
		float CURRENT_DAY_QUOTE_VOLUME { get; set; }
		float CURRENT_DAY_QUOTE_VOLUME_BUY { get; set; }
		float CURRENT_DAY_QUOTE_VOLUME_SELL { get; set; }
		int CURRENT_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int CURRENT_DAY_TOTAL_TRADES { get; set; }
		int CURRENT_DAY_TOTAL_TRADES_BUY { get; set; }
		int CURRENT_DAY_TOTAL_TRADES_SELL { get; set; }
		int CURRENT_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float CURRENT_DAY_VOLUME { get; set; }
		float CURRENT_DAY_VOLUME_BUY { get; set; }
		float CURRENT_DAY_VOLUME_SELL { get; set; }
		int CURRENT_DAY_VOLUME_UNKNOWN { get; set; }
		float CURRENT_HOUR_HIGH { get; set; }
		float CURRENT_HOUR_CHANGE { get; set; }
		float CURRENT_HOUR_CHANGE_PERCENTAGE { get; set; }
		float CURRENT_HOUR_LOW { get; set; }
		float CURRENT_HOUR_OPEN { get; set; }
		float CURRENT_HOUR_QUOTE_VOLUME { get; set; }
		float CURRENT_HOUR_QUOTE_VOLUME_BUY { get; set; }
		float CURRENT_HOUR_QUOTE_VOLUME_SELL { get; set; }
		int CURRENT_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		int CURRENT_HOUR_TOTAL_TRADES { get; set; }
		int CURRENT_HOUR_TOTAL_TRADES_BUY { get; set; }
		int CURRENT_HOUR_TOTAL_TRADES_SELL { get; set; }
		int CURRENT_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		float CURRENT_HOUR_VOLUME { get; set; }
		float CURRENT_HOUR_VOLUME_BUY { get; set; }
		float CURRENT_HOUR_VOLUME_SELL { get; set; }
		int CURRENT_HOUR_VOLUME_UNKNOWN { get; set; }
		float CURRENT_MONTH_HIGH { get; set; }
		float CURRENT_MONTH_CHANGE { get; set; }
		float CURRENT_MONTH_CHANGE_PERCENTAGE { get; set; }
		int CURRENT_MONTH_LOW { get; set; }
		float CURRENT_MONTH_OPEN { get; set; }
		float CURRENT_MONTH_QUOTE_VOLUME { get; set; }
		float CURRENT_MONTH_QUOTE_VOLUME_BUY { get; set; }
		float CURRENT_MONTH_QUOTE_VOLUME_SELL { get; set; }
		int CURRENT_MONTH_QUOTE_VOLUME_UNKNOWN { get; set; }
		int CURRENT_MONTH_TOTAL_TRADES { get; set; }
		int CURRENT_MONTH_TOTAL_TRADES_BUY { get; set; }
		int CURRENT_MONTH_TOTAL_TRADES_SELL { get; set; }
		int CURRENT_MONTH_TOTAL_TRADES_UNKNOWN { get; set; }
		float CURRENT_MONTH_VOLUME { get; set; }
		float CURRENT_MONTH_VOLUME_BUY { get; set; }
		float CURRENT_MONTH_VOLUME_SELL { get; set; }
		int CURRENT_MONTH_VOLUME_UNKNOWN { get; set; }
		float CURRENT_WEEK_HIGH { get; set; }
		float CURRENT_WEEK_CHANGE { get; set; }
		float CURRENT_WEEK_CHANGE_PERCENTAGE { get; set; }
		float CURRENT_WEEK_LOW { get; set; }
		float CURRENT_WEEK_OPEN { get; set; }
		float CURRENT_WEEK_QUOTE_VOLUME { get; set; }
		float CURRENT_WEEK_QUOTE_VOLUME_BUY { get; set; }
		float CURRENT_WEEK_QUOTE_VOLUME_SELL { get; set; }
		int CURRENT_WEEK_QUOTE_VOLUME_UNKNOWN { get; set; }
		int CURRENT_WEEK_TOTAL_TRADES { get; set; }
		int CURRENT_WEEK_TOTAL_TRADES_BUY { get; set; }
		int CURRENT_WEEK_TOTAL_TRADES_SELL { get; set; }
		int CURRENT_WEEK_TOTAL_TRADES_UNKNOWN { get; set; }
		float CURRENT_WEEK_VOLUME { get; set; }
		float CURRENT_WEEK_VOLUME_BUY { get; set; }
		float CURRENT_WEEK_VOLUME_SELL { get; set; }
		int CURRENT_WEEK_VOLUME_UNKNOWN { get; set; }
		float CURRENT_YEAR_HIGH { get; set; }
		float CURRENT_YEAR_CHANGE { get; set; }
		float CURRENT_YEAR_CHANGE_PERCENTAGE { get; set; }
		int CURRENT_YEAR_LOW { get; set; }
		float CURRENT_YEAR_OPEN { get; set; }
		float CURRENT_YEAR_QUOTE_VOLUME { get; set; }
		float CURRENT_YEAR_QUOTE_VOLUME_BUY { get; set; }
		float CURRENT_YEAR_QUOTE_VOLUME_SELL { get; set; }
		int CURRENT_YEAR_QUOTE_VOLUME_UNKNOWN { get; set; }
		int CURRENT_YEAR_TOTAL_TRADES { get; set; }
		int CURRENT_YEAR_TOTAL_TRADES_BUY { get; set; }
		int CURRENT_YEAR_TOTAL_TRADES_SELL { get; set; }
		int CURRENT_YEAR_TOTAL_TRADES_UNKNOWN { get; set; }
		float CURRENT_YEAR_VOLUME { get; set; }
		float CURRENT_YEAR_VOLUME_BUY { get; set; }
		float CURRENT_YEAR_VOLUME_SELL { get; set; }
		int CURRENT_YEAR_VOLUME_UNKNOWN { get; set; }
		string INSTRUMENT { get; set; }
		int LAST_PROCESSED_TRADE_CCSEQ { get; set; }
		float LAST_PROCESSED_TRADE_PRICE { get; set; }
		float LAST_PROCESSED_TRADE_QUANTITY { get; set; }
		float LAST_PROCESSED_TRADE_QUOTE_QUANTITY { get; set; }
		string LAST_PROCESSED_TRADE_SIDE { get; set; }
		int LAST_PROCESSED_TRADE_TS { get; set; }
		int LAST_PROCESSED_TRADE_TS_NS { get; set; }
		int LAST_TRADE_CCSEQ { get; set; }
		string LAST_TRADE_ID { get; set; }
		float LAST_TRADE_QUANTITY { get; set; }
		float LAST_TRADE_QUOTE_QUANTITY { get; set; }
		string LAST_TRADE_SIDE { get; set; }
		int LIFETIME_FIRST_TRADE_TS { get; set; }
		float LIFETIME_HIGH { get; set; }
		int LIFETIME_HIGH_TS { get; set; }
		float LIFETIME_CHANGE { get; set; }
		float LIFETIME_CHANGE_PERCENTAGE { get; set; }
		float LIFETIME_LOW { get; set; }
		int LIFETIME_LOW_TS { get; set; }
		int LIFETIME_OPEN { get; set; }
		float LIFETIME_QUOTE_VOLUME { get; set; }
		float LIFETIME_QUOTE_VOLUME_BUY { get; set; }
		float LIFETIME_QUOTE_VOLUME_SELL { get; set; }
		int LIFETIME_QUOTE_VOLUME_UNKNOWN { get; set; }
		int LIFETIME_TOTAL_TRADES { get; set; }
		int LIFETIME_TOTAL_TRADES_BUY { get; set; }
		int LIFETIME_TOTAL_TRADES_SELL { get; set; }
		int LIFETIME_TOTAL_TRADES_UNKNOWN { get; set; }
		float LIFETIME_VOLUME { get; set; }
		float LIFETIME_VOLUME_BUY { get; set; }
		float LIFETIME_VOLUME_SELL { get; set; }
		int LIFETIME_VOLUME_UNKNOWN { get; set; }
		string MAPPED_INSTRUMENT { get; set; }
		string MARKET { get; set; }
		float MOVING_180_DAY_HIGH { get; set; }
		float MOVING_180_DAY_CHANGE { get; set; }
		float MOVING_180_DAY_CHANGE_PERCENTAGE { get; set; }
		float MOVING_180_DAY_LOW { get; set; }
		float MOVING_180_DAY_OPEN { get; set; }
		float MOVING_180_DAY_QUOTE_VOLUME { get; set; }
		float MOVING_180_DAY_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_180_DAY_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_180_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_180_DAY_TOTAL_TRADES { get; set; }
		int MOVING_180_DAY_TOTAL_TRADES_BUY { get; set; }
		int MOVING_180_DAY_TOTAL_TRADES_SELL { get; set; }
		int MOVING_180_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_180_DAY_VOLUME { get; set; }
		float MOVING_180_DAY_VOLUME_BUY { get; set; }
		float MOVING_180_DAY_VOLUME_SELL { get; set; }
		int MOVING_180_DAY_VOLUME_UNKNOWN { get; set; }
		float MOVING_24_HOUR_HIGH { get; set; }
		float MOVING_24_HOUR_CHANGE { get; set; }
		float MOVING_24_HOUR_CHANGE_PERCENTAGE { get; set; }
		float MOVING_24_HOUR_LOW { get; set; }
		float MOVING_24_HOUR_OPEN { get; set; }
		float MOVING_24_HOUR_QUOTE_VOLUME { get; set; }
		float MOVING_24_HOUR_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_24_HOUR_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_24_HOUR_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_24_HOUR_TOTAL_TRADES { get; set; }
		int MOVING_24_HOUR_TOTAL_TRADES_BUY { get; set; }
		int MOVING_24_HOUR_TOTAL_TRADES_SELL { get; set; }
		int MOVING_24_HOUR_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_24_HOUR_VOLUME { get; set; }
		float MOVING_24_HOUR_VOLUME_BUY { get; set; }
		float MOVING_24_HOUR_VOLUME_SELL { get; set; }
		int MOVING_24_HOUR_VOLUME_UNKNOWN { get; set; }
		float MOVING_30_DAY_HIGH { get; set; }
		float MOVING_30_DAY_CHANGE { get; set; }
		float MOVING_30_DAY_CHANGE_PERCENTAGE { get; set; }
		int MOVING_30_DAY_LOW { get; set; }
		float MOVING_30_DAY_OPEN { get; set; }
		float MOVING_30_DAY_QUOTE_VOLUME { get; set; }
		float MOVING_30_DAY_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_30_DAY_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_30_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_30_DAY_TOTAL_TRADES { get; set; }
		int MOVING_30_DAY_TOTAL_TRADES_BUY { get; set; }
		int MOVING_30_DAY_TOTAL_TRADES_SELL { get; set; }
		int MOVING_30_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_30_DAY_VOLUME { get; set; }
		float MOVING_30_DAY_VOLUME_BUY { get; set; }
		float MOVING_30_DAY_VOLUME_SELL { get; set; }
		int MOVING_30_DAY_VOLUME_UNKNOWN { get; set; }
		float MOVING_365_DAY_HIGH { get; set; }
		float MOVING_365_DAY_CHANGE { get; set; }
		float MOVING_365_DAY_CHANGE_PERCENTAGE { get; set; }
		int MOVING_365_DAY_LOW { get; set; }
		float MOVING_365_DAY_OPEN { get; set; }
		float MOVING_365_DAY_QUOTE_VOLUME { get; set; }
		float MOVING_365_DAY_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_365_DAY_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_365_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_365_DAY_TOTAL_TRADES { get; set; }
		int MOVING_365_DAY_TOTAL_TRADES_BUY { get; set; }
		int MOVING_365_DAY_TOTAL_TRADES_SELL { get; set; }
		int MOVING_365_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_365_DAY_VOLUME { get; set; }
		float MOVING_365_DAY_VOLUME_BUY { get; set; }
		float MOVING_365_DAY_VOLUME_SELL { get; set; }
		int MOVING_365_DAY_VOLUME_UNKNOWN { get; set; }
		float MOVING_7_DAY_HIGH { get; set; }
		float MOVING_7_DAY_CHANGE { get; set; }
		float MOVING_7_DAY_CHANGE_PERCENTAGE { get; set; }
		int MOVING_7_DAY_LOW { get; set; }
		float MOVING_7_DAY_OPEN { get; set; }
		float MOVING_7_DAY_QUOTE_VOLUME { get; set; }
		float MOVING_7_DAY_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_7_DAY_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_7_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_7_DAY_TOTAL_TRADES { get; set; }
		int MOVING_7_DAY_TOTAL_TRADES_BUY { get; set; }
		int MOVING_7_DAY_TOTAL_TRADES_SELL { get; set; }
		int MOVING_7_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_7_DAY_VOLUME { get; set; }
		float MOVING_7_DAY_VOLUME_BUY { get; set; }
		float MOVING_7_DAY_VOLUME_SELL { get; set; }
		int MOVING_7_DAY_VOLUME_UNKNOWN { get; set; }
		float MOVING_90_DAY_HIGH { get; set; }
		float MOVING_90_DAY_CHANGE { get; set; }
		float MOVING_90_DAY_CHANGE_PERCENTAGE { get; set; }
		int MOVING_90_DAY_LOW { get; set; }
		float MOVING_90_DAY_OPEN { get; set; }
		float MOVING_90_DAY_QUOTE_VOLUME { get; set; }
		float MOVING_90_DAY_QUOTE_VOLUME_BUY { get; set; }
		float MOVING_90_DAY_QUOTE_VOLUME_SELL { get; set; }
		int MOVING_90_DAY_QUOTE_VOLUME_UNKNOWN { get; set; }
		int MOVING_90_DAY_TOTAL_TRADES { get; set; }
		int MOVING_90_DAY_TOTAL_TRADES_BUY { get; set; }
		int MOVING_90_DAY_TOTAL_TRADES_SELL { get; set; }
		int MOVING_90_DAY_TOTAL_TRADES_UNKNOWN { get; set; }
		float MOVING_90_DAY_VOLUME { get; set; }
		float MOVING_90_DAY_VOLUME_BUY { get; set; }
		float MOVING_90_DAY_VOLUME_SELL { get; set; }
		int MOVING_90_DAY_VOLUME_UNKNOWN { get; set; }
		float PRICE { get; set; }
		string PRICE_FLAG { get; set; }
		int PRICE_LAST_UPDATE_TS { get; set; }
		int PRICE_LAST_UPDATE_TS_NS { get; set; }
		string QUOTE { get; set; }
		int QUOTE_ID { get; set; }
		string TRANSFORM_FUNCTION { get; set; }
		string TYPE { get; set; }
	}
}